### ISSUE TITLE
Update to 1.20.6

### ISSUE THREAD

**Issue by BRNSystems** [Patbox/PolyFactory#15]
Will this be updated to 1.20.6?

**Comment by Patbox** [comment]
Yes it will. Currently waiting for GraphLib to update, as PolyFactory heavily depends on it

**Comment by BRNSystems** [comment]
I looked here: https://github.com/Kneelawk/GraphLib/blob/wip/2.0-1/gradle.properties
It has 1.20.6

**Comment by Patbox** [comment]
It isn't yet finished (or in working state yet). I have contact with the developer of it.
