### ISSUE TITLE
The synthesis method cannot be displayed correctly and the usage of items is unclear.

### ISSUE THREAD

**Issue by QianMuu** [Patbox/PolyFactory#21]
First point: The synthesis method may not be perfect enough. I can't clearly know how the copper plate is made (JEI). There are many similar ones.
Second point: Some machines have no instructions, so most machines don't know how to use them. Maybe you can improve this shortcoming.
(Make a book or add item introduction)

**Comment by Patbox** [comment]
I slowly work on a wiki, which should help with lack of informations ( https://modded.wiki/w/Mod:PolyFactory ). Additionally this mod doesn't support JEI (or any other client recipe viewer out of the box). Officially only supported way to see recipes is [Polydex](https://modrinth.com/mod/polydex) through for more classic experience you can use it with [Polydex Bridge](https://modrinth.com/mod/polydex-bridge) and [EMI](https://modrinth.com/mod/emi).
