### ISSUE TITLE
Cannot remap to MojMap

### ISSUE THREAD

**Issue by gkgoat1** [Patbox/PolyFactory#22]
I am making a NeoForge modpack, using Connector to also include fabric mods and Architectury loom to orchestrate the whole thing. I want to include Polyfactory, but it does not remap.

```Mapping target name conflicts detected:
  METHODs eu/pb4/polyfactory/recipe/FillSprayCanCraftingRecipe/[category, net/minecraft/class_3955/method_45441]()Lnet/minecraft/class_7710; -> category
There were unfixable conflicts.```

**Comment by Patbox** [comment]
NeoForge/Connector aren't supported by this mod (and libraries it uses). Any issue should be reported to them anyway
