### ISSUE TITLE
[Question] Polyfactory 1.20.1 backport?

### ISSUE THREAD

**Issue by lostopkk** [Patbox/PolyFactory#4]
There aren't many mods for 1.20.2 I wanted to know if it is possible that there could be a backport to 1.20.1 or 1.19.2?

**Comment by Patbox** [comment]
1.19.2 is out of the question, as it's going to be practically impossible.
1.20.1 would be possible if you cut out functional waterlogging (older dev builds also run on it), but I don't plan on backporting this, as there isn't much benefit, as people will move on to next main release anyway (which will happen in few months, possibly next summer) This mod will also likely keep up with Mojang releases (1.20.3, 1.20.4 if that happens)

**Comment by lostopkk** [comment]
> 1.19.2 is out of the question, as it's going to be practically impossible. 1.20.1 would be possible if you cut out functional waterlogging (older dev builds also run on it), but I don't plan on backporting this, as there isn't much benefit, as people will move on to next main release anyway (which will happen in few months, possibly next summer) This mod will also likely keep up with Mojang releases (1.20.3, 1.20.4 if that happens)

Thanks for the answer, I loved the mod! I just wanted to be able to add it to my server but it is 1.20.1 for now... when several ports of the mods I use go to 1.20.2, I won't hesitate in adding it :)
