### ISSUE TITLE
[request] Copper/brass gears?

### ISSUE THREAD

**Issue by nycki93** [Patbox/PolyFactory#6]
Iron is already such a tight resource in vanilla minecraft. Could we have an option to change the recipe and texture to be copper-based?

**Comment by Patbox** [comment]
You should be able to do this with a datapack and an asset override in polymer (putting assets in `polymer/override_assets`, same as resource packs)

**Comment by Patbox** [comment]
But I might look into tweaking the recipe

**Comment by Patbox** [comment]
You now get 2 gears instead of one, but will look into this more in the future likely
